default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: toolbox_development

test:
  <<: *default
  database: toolbox_test

production:
  <<: *default
  database: toolbox_production
  username: toolbox
  password: <%= ENV['TOOLBOX_DATABASE_PASSWORD'] %>
