# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e603328b3a168300f68a44bf102d502edd526dfe1fd4053ebd743b172fa32aeadf3c044714cfa4930b47ad63308902080884319822b1ef04e870aff49ff3d2a

test:
  secret_key_base: f551f62125e92de3a812c49edb7eefa6621488fc952ef9aab9dce032cb53268e30b310adb487882e133c626aaed84c1bdf6ea610a72d5a8d5998703f0bfc1bc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
